"""
ChArUco camera calibration : intrinsics (K, dist) from multi-view ChArUco board.

Workflow :
  1. Print a ChArUco board (use make_charuco_board().generateImage() then save).
  2. Capture ~15-30 views of the board, tilted at various angles in front of
     the camera. Coverage of the entire image area is more important than the
     board size (a small board moved around works well).
  3. detect_charuco(...) on each view -> corners + ids.
  4. calibrate_intrinsics(views, board) -> K, dist, RMS px error.
  5. Save with CameraIntrinsics.save() ; load with CameraIntrinsics.load().

Once K, dist are known, downstream code can :
  - undistort images (cv2.undistort or cv2.remap with cv2.initUndistortRectifyMap)
  - detect 4 ArUco anchors at known mm positions on the table
  - cv2.solvePnP(K, dist, anchor_3D, anchor_2D) -> R, T (camera pose vs table)
  - build a homography H = K * [r1 r2 t] for the table plane (Z=0)
  - render a top-down BEV via cv2.warpPerspective with H_inv
"""

from __future__ import annotations

import json
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

import cv2
import numpy as np


# Default board geometry : 9x6 squares of 30 mm with 22 mm ArUco markers.
# Fits on A4 (270 x 180 mm). User can change before generating.
DEFAULT_SQUARES_X = 9
DEFAULT_SQUARES_Y = 6
DEFAULT_SQUARE_MM = 30.0
DEFAULT_MARKER_MM = 22.0
DEFAULT_DICT_NAME = "5x5_100"

# Comprehensive list of ArUco dictionaries supported by OpenCV.
# Calib.io ChArUco boards typically use one of these. The name in their
# print legend usually matches a key here (e.g., "DICT_4X4_50" -> "4x4_50").
_ARUCO_DICTS = {
    "4x4_50":             cv2.aruco.DICT_4X4_50,
    "4x4_100":            cv2.aruco.DICT_4X4_100,
    "4x4_250":            cv2.aruco.DICT_4X4_250,
    "4x4_1000":           cv2.aruco.DICT_4X4_1000,
    "5x5_50":             cv2.aruco.DICT_5X5_50,
    "5x5_100":            cv2.aruco.DICT_5X5_100,
    "5x5_250":            cv2.aruco.DICT_5X5_250,
    "5x5_1000":           cv2.aruco.DICT_5X5_1000,
    "6x6_50":             cv2.aruco.DICT_6X6_50,
    "6x6_100":            cv2.aruco.DICT_6X6_100,
    "6x6_250":            cv2.aruco.DICT_6X6_250,
    "6x6_1000":           cv2.aruco.DICT_6X6_1000,
    "7x7_50":             cv2.aruco.DICT_7X7_50,
    "7x7_100":            cv2.aruco.DICT_7X7_100,
    "7x7_250":            cv2.aruco.DICT_7X7_250,
    "7x7_1000":           cv2.aruco.DICT_7X7_1000,
    "ARUCO_ORIGINAL":     cv2.aruco.DICT_ARUCO_ORIGINAL,
    "APRILTAG_16h5":      cv2.aruco.DICT_APRILTAG_16h5,
    "APRILTAG_25h9":      cv2.aruco.DICT_APRILTAG_25h9,
    "APRILTAG_36h10":     cv2.aruco.DICT_APRILTAG_36h10,
    "APRILTAG_36h11":     cv2.aruco.DICT_APRILTAG_36h11,
}


def make_charuco_board(
    squares_x: int = DEFAULT_SQUARES_X,
    squares_y: int = DEFAULT_SQUARES_Y,
    square_mm: float = DEFAULT_SQUARE_MM,
    marker_mm: float = DEFAULT_MARKER_MM,
    dict_name: str = DEFAULT_DICT_NAME,
    legacy_pattern: bool = True,
):
    """Build a cv2.aruco.CharucoBoard with metric square/marker sizes.

    legacy_pattern : OpenCV 4.6 reversed the marker placement convention on
    ChArUco boards. Boards printed with calib.io (and most older sources) use
    the LEGACY layout. Set legacy_pattern=True if your printed board was
    generated by calib.io or any pre-4.6 OpenCV version. This affects only the
    detector's expected layout, not the printed image.
    """
    dict_id = _ARUCO_DICTS.get(dict_name, cv2.aruco.DICT_5X5_100)
    aruco_dict = cv2.aruco.getPredefinedDictionary(dict_id)
    board = cv2.aruco.CharucoBoard(
        (squares_x, squares_y), float(square_mm), float(marker_mm), aruco_dict,
    )
    if legacy_pattern:
        try:
            board.setLegacyPattern(True)
        except AttributeError:
            # Older OpenCV without the API ; the pattern is already legacy.
            pass
    return board, aruco_dict


def render_board_image(board, px_per_mm: float = 6.0, margin_px: int = 30) -> np.ndarray:
    """Render a high-resolution image of the board ready to print.
    Default 6 px/mm = ~150 DPI, suitable for A4."""
    sq_x, sq_y = board.getChessboardSize()
    sq_mm = board.getSquareLength()
    w = int(sq_x * sq_mm * px_per_mm) + 2 * margin_px
    h = int(sq_y * sq_mm * px_per_mm) + 2 * margin_px
    img = board.generateImage((w, h), marginSize=margin_px)
    return img


def detect_charuco(
    image: np.ndarray, board, aruco_dict,
):
    """Detect ChArUco corners on a single image.
    Returns (corners, ids) ready for calibrateCameraCharuco, or (None, None) if
    insufficient detections."""
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY) if image.ndim == 3 else image
    detector = cv2.aruco.CharucoDetector(board)
    char_corners, char_ids, marker_corners, marker_ids = detector.detectBoard(gray)
    if char_corners is None or char_ids is None or len(char_ids) < 4:
        return None, None
    return char_corners, char_ids


@dataclass
class CalibrationView:
    """One captured ChArUco view : corners + ids + image size."""
    corners: np.ndarray
    ids: np.ndarray
    image_size: tuple[int, int]   # (W, H)
    n_corners: int = 0

    def __post_init__(self):
        if self.corners is not None:
            self.n_corners = int(len(self.corners))


def calibrate_intrinsics(
    views: list[CalibrationView],
    board,
    use_fisheye: bool = False,
    flags_extra: int = 0,
):
    """Run cv2.aruco.calibrateCameraCharuco (or fisheye variant) over a list
    of views. Returns (K, dist, rms_px, per_view_pose) where per_view_pose is
    a list of (rvec, tvec) for each view."""
    if len(views) < 3:
        raise RuntimeError("Need at least 3 views, ideally 15+ at varied angles.")

    # Filter out views with too few corners
    valid = [v for v in views if v.n_corners >= 6]
    if len(valid) < 3:
        raise RuntimeError(
            f"Only {len(valid)} views with >=6 corners; need 3+. Add more "
            "views with the board well-detected."
        )

    image_size = valid[0].image_size
    all_corners = [v.corners for v in valid]
    all_ids = [v.ids for v in valid]

    if use_fisheye:
        # cv2.fisheye expects (N, 1, 3) and (N, 1, 2) per-view
        obj_pts_list = []
        img_pts_list = []
        for c, ids in zip(all_corners, all_ids):
            obj_pts, img_pts = board.matchImagePoints(c, ids)
            if obj_pts is None or len(obj_pts) < 4:
                continue
            obj_pts_list.append(obj_pts.reshape(-1, 1, 3).astype(np.float64))
            img_pts_list.append(img_pts.reshape(-1, 1, 2).astype(np.float64))
        if len(obj_pts_list) < 3:
            raise RuntimeError("Not enough valid views for fisheye calibration.")
        K = np.zeros((3, 3))
        D = np.zeros((4, 1))
        flags = (
            cv2.fisheye.CALIB_RECOMPUTE_EXTRINSIC
            | cv2.fisheye.CALIB_FIX_SKEW
            | flags_extra
        )
        rms, K, D, rvecs, tvecs = cv2.fisheye.calibrate(
            obj_pts_list, img_pts_list, image_size, K, D, flags=flags,
        )
        per_view = [(r, t) for r, t in zip(rvecs, tvecs)]
        return K.astype(np.float64), D.astype(np.float64), float(rms), per_view

    # Standard pinhole + rational + thin prism + tilted distortion model
    flags = (
        cv2.CALIB_RATIONAL_MODEL
        | cv2.CALIB_THIN_PRISM_MODEL
        | flags_extra
    )
    try:
        rms, K, D, rvecs, tvecs = cv2.aruco.calibrateCameraCharuco(
            all_corners, all_ids, board, image_size, None, None, flags=flags,
        )
    except cv2.error as e:
        # Fall back to standard distortion if rational/thin prism fails
        flags = flags_extra
        rms, K, D, rvecs, tvecs = cv2.aruco.calibrateCameraCharuco(
            all_corners, all_ids, board, image_size, None, None, flags=flags,
        )
    per_view = [(r, t) for r, t in zip(rvecs, tvecs)]
    return K.astype(np.float64), D.astype(np.float64), float(rms), per_view


@dataclass
class CameraIntrinsics:
    """Camera intrinsics : K, dist, image size, calibration metadata."""
    K: np.ndarray
    dist: np.ndarray
    image_size: tuple[int, int]
    rms_px: float = 0.0
    n_views: int = 0
    model: str = "standard"   # "standard" or "fisheye"
    board_squares_x: int = DEFAULT_SQUARES_X
    board_squares_y: int = DEFAULT_SQUARES_Y
    board_square_mm: float = DEFAULT_SQUARE_MM
    board_marker_mm: float = DEFAULT_MARKER_MM
    board_dict: str = DEFAULT_DICT_NAME
    calibrated_at: str = ""

    def to_dict(self):
        return {
            "type": "camera_intrinsics",
            "model": self.model,
            "K": self.K.tolist(),
            "dist": self.dist.tolist(),
            "image_size": list(self.image_size),
            "rms_px": self.rms_px,
            "n_views": self.n_views,
            "board": {
                "squares_x": self.board_squares_x,
                "squares_y": self.board_squares_y,
                "square_mm": self.board_square_mm,
                "marker_mm": self.board_marker_mm,
                "dict": self.board_dict,
            },
            "calibrated_at": self.calibrated_at,
        }

    def save(self, path: str | Path):
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        with open(path, "w") as f:
            json.dump(self.to_dict(), f, indent=2)

    @classmethod
    def from_dict(cls, d: dict) -> "CameraIntrinsics":
        b = d.get("board", {})
        return cls(
            K=np.array(d["K"], dtype=np.float64),
            dist=np.array(d["dist"], dtype=np.float64),
            image_size=tuple(d["image_size"]),
            rms_px=float(d.get("rms_px", 0.0)),
            n_views=int(d.get("n_views", 0)),
            model=d.get("model", "standard"),
            board_squares_x=int(b.get("squares_x", DEFAULT_SQUARES_X)),
            board_squares_y=int(b.get("squares_y", DEFAULT_SQUARES_Y)),
            board_square_mm=float(b.get("square_mm", DEFAULT_SQUARE_MM)),
            board_marker_mm=float(b.get("marker_mm", DEFAULT_MARKER_MM)),
            board_dict=str(b.get("dict", DEFAULT_DICT_NAME)),
            calibrated_at=d.get("calibrated_at", ""),
        )

    @classmethod
    def load(cls, path: str | Path) -> "CameraIntrinsics":
        with open(path, "r") as f:
            return cls.from_dict(json.load(f))

    # -------- Live use (per frame solvePnP for table pose) ----------------

    def estimate_table_pose(
        self, anchor_pixels: np.ndarray, anchor_mm: np.ndarray,
        z_mm: float = 0.0,
    ):
        """Given 4 (or more) detected anchor pixel centers + their known mm
        positions on the table plane (Z = z_mm), return (R, T) of the camera
        pose. Use cv2.solvePnP."""
        if len(anchor_pixels) < 4 or len(anchor_mm) < 4:
            raise ValueError("Need at least 4 anchors")
        obj = np.column_stack([
            np.asarray(anchor_mm, dtype=np.float32),
            np.full((len(anchor_mm), 1), float(z_mm), dtype=np.float32),
        ])
        img = np.asarray(anchor_pixels, dtype=np.float32)
        flags = cv2.SOLVEPNP_IPPE if len(obj) == 4 else cv2.SOLVEPNP_ITERATIVE
        ok, rvec, tvec = cv2.solvePnP(obj, img, self.K, self.dist, flags=flags)
        if not ok:
            raise RuntimeError("solvePnP failed.")
        R, _ = cv2.Rodrigues(rvec)
        return R, tvec, rvec

    def homography_table_to_pixel(self, R: np.ndarray, T: np.ndarray) -> np.ndarray:
        """Return the 3x3 homography H mapping table-plane (X_mm, Y_mm, 1)
        to image pixel (u, v, 1). H = K * [r1 r2 t]."""
        H = self.K @ np.column_stack([R[:, 0], R[:, 1], T.ravel()])
        return H

    def undistort_points(self, points_pixel: np.ndarray) -> np.ndarray:
        """Undistort image pixel points (N, 2) -> (N, 2) undistorted pixel."""
        pts = np.asarray(points_pixel, dtype=np.float32).reshape(-1, 1, 2)
        und = cv2.undistortPoints(pts, self.K, self.dist, P=self.K)
        return und.reshape(-1, 2)

    def build_undistort_maps(self, image_size: Optional[tuple[int, int]] = None,
                              alpha: float = 0.0):
        """Pre-compute remap maps (mx, my) for fast cv2.remap undistortion.
        alpha=0 keeps only valid pixels ; alpha=1 keeps all pixels with black
        borders."""
        size = image_size or self.image_size
        if self.model == "fisheye":
            new_K = cv2.fisheye.estimateNewCameraMatrixForUndistortRectify(
                self.K, self.dist, size, R=np.eye(3), balance=alpha,
            )
            mx, my = cv2.fisheye.initUndistortRectifyMap(
                self.K, self.dist, R=np.eye(3), P=new_K, size=size,
                m1type=cv2.CV_16SC2,
            )
        else:
            new_K, _ = cv2.getOptimalNewCameraMatrix(
                self.K, self.dist, size, alpha=alpha,
            )
            mx, my = cv2.initUndistortRectifyMap(
                self.K, self.dist, R=None, newCameraMatrix=new_K, size=size,
                m1type=cv2.CV_16SC2,
            )
        return mx, my, new_K
