/**
 * services/mission/mission_controller.cpp — Fallback Mission Executor
 *
 * Loads /mission_fallback.cfg from SD and executes each command line
 * sequentially via the firmware command dispatcher.
 *
 * The strategy file is a plain-text sequence generated by holOS:
 *   # Comment
 *   go(300,400)
 *   turn(90.0)
 *   delay(500)
 *   actuator_cmd(...)
 *
 * Execution model:
 *   - One command per line (comments stripped)
 *   - Motion commands (go, turn, goPolar, align) are executed synchronously:
 *     command is dispatched, then we poll motion.hasFinished() up to 30 s
 *   - delay(ms) is implemented natively (busy-wait with delay())
 *   - All other commands are dispatched and assumed instantaneous
 */

#include "mission_controller.h"
#include "services/sd/sd_card.h"
#include "services/motion/motion.h"
#include "os/console.h"
#include "os/os.h"
#include "utils/commandHandler.h"

#include <Arduino.h>

// motion is declared via SINGLETON_EXTERN(Motion, motion) in motion.h — no extern needed

namespace MissionController {

// ── Internal state ────────────────────────────────────────────────────────────

static constexpr size_t MAX_LINES = 256;
static constexpr size_t LINE_LEN  = MAX_LINE_LEN;

/// Loaded command lines (stripped, no comments).
/// DMAMEM → placed in RAM2 (OCRAM, 512 KB free) instead of RAM1 (DTCM, 512 KB total).
/// s_cmds is 32 KB — far too large for RAM1. Mission execution is not time-critical
/// so the slightly higher RAM2 latency is irrelevant.
static DMAMEM char  s_cmds[MAX_LINES][LINE_LEN];
static size_t s_cmdCount   = 0;
static bool  s_loaded     = false;
static bool  s_running    = false;
static bool  s_abort      = false;

// ── Motion-command detection ──────────────────────────────────────────────────

static const char* MOTION_PREFIXES[] = {
    "go(", "go_coc(", "goPolar(", "turn(", "align(", "goAlign(", "move(", nullptr
};

static bool isMotionCmd(const char* line) {
    for (int i = 0; MOTION_PREFIXES[i]; ++i) {
        if (strncmp(line, MOTION_PREFIXES[i], strlen(MOTION_PREFIXES[i])) == 0) {
            return true;
        }
    }
    return false;
}

// ── delay(ms) parsing ─────────────────────────────────────────────────────────

static bool tryDelay(const char* line) {
    if (strncmp(line, "delay(", 6) != 0) return false;
    int ms = atoi(line + 6);
    if (ms > 0 && ms < 60000) delay((unsigned long)ms);
    return true;
}

// ── Helpers ───────────────────────────────────────────────────────────────────

static void stripLine(const char* src, char* dst, size_t dstLen) {
    // Copy until '#' or end, then strip trailing whitespace
    size_t i = 0, j = 0;
    while (src[i] && src[i] != '#' && j + 1 < dstLen) {
        dst[j++] = src[i++];
    }
    // Trim trailing whitespace
    while (j > 0 && (dst[j-1] == ' ' || dst[j-1] == '\t' ||
                     dst[j-1] == '\r' || dst[j-1] == '\n')) {
        j--;
    }
    dst[j] = '\0';
}

// ── Public API ────────────────────────────────────────────────────────────────

FLASHMEM bool load() {
    s_loaded   = false;
    s_cmdCount = 0;

    if (!SDCard::isReady()) {
        Console::warn("Mission") << "SD not ready — no fallback" << Console::endl;
        return false;
    }

    // DMAMEM: 8KB read buffer in RAM2 instead of stack — load() is not reentrant.
    static DMAMEM char buf[MAX_FILE_SIZE];
    if (!SDCard::load(FALLBACK_PATH, buf, sizeof(buf))) {
        Console::warn("Mission") << "No fallback file on SD" << Console::endl;
        return false;
    }

    // Parse line by line
    char line[LINE_LEN];
    const char* p = buf;
    while (*p && s_cmdCount < MAX_LINES) {
        // Extract next line
        int len = 0;
        while (*p && *p != '\n' && *p != '\r' && len + 1 < (int)LINE_LEN) {
            line[len++] = *p++;
        }
        line[len] = '\0';
        // Skip CR/LF
        while (*p == '\n' || *p == '\r') p++;

        // Strip comments, trim whitespace
        char stripped[LINE_LEN];
        stripLine(line, stripped, sizeof(stripped));
        if (stripped[0] == '\0') continue;   // blank / pure comment

        strncpy(s_cmds[s_cmdCount], stripped, LINE_LEN - 1);
        s_cmds[s_cmdCount][LINE_LEN - 1] = '\0';
        s_cmdCount++;
    }

    s_loaded = s_cmdCount > 0;
    Console::info("Mission") << "Loaded " << s_cmdCount
                              << " commands from " << FALLBACK_PATH << Console::endl;
    return s_loaded;
}

bool isLoaded() { return s_loaded; }
bool isRunning() { return s_running; }

void abort() {
    s_abort = true;
    motion.cancel();   // stop ongoing motion immediately
}

FLASHMEM void execute() {
    if (!s_loaded || s_cmdCount == 0) {
        Console::warn("Mission") << "No strategy loaded — aborting fallback" << Console::endl;
        return;
    }

    s_running = true;
    s_abort   = false;

    Console::info("Mission") << "═══ Fallback strategy start ("
                              << s_cmdCount << " cmds) ═══" << Console::endl;

    for (size_t i = 0; i < s_cmdCount && !s_abort; ++i) {
        const char* cmd = s_cmds[i];
        Console::info("Mission") << "[" << (i+1) << "/" << s_cmdCount << "] " << cmd << Console::endl;

        // ── delay(ms) — native implementation ─────────────────────────────
        if (tryDelay(cmd)) continue;

        // ── Motion commands — dispatch + wait for completion ───────────────
        if (isMotionCmd(cmd)) {
            String scmd(cmd);
            os.execute(scmd);   // routes through Program (friend of CommandHandler)
            // Wait for motion to complete (up to 30 s)
            unsigned long t0 = millis();
            while (!motion.hasFinished() && (millis() - t0) < 30000UL && !s_abort) {
                delay(20);
            }
            if (!motion.wasSuccessful()) {
                Console::warn("Mission") << "Motion failed — continuing" << Console::endl;
            }
            continue;
        }

        // ── Generic command — dispatch as-is via OS interpreter ──────────
        {
            String scmd(cmd);
            // Append parentheses if the command has none (bare name), so the
            // interpreter can parse it as a valid command statement.
            if (scmd.indexOf('(') < 0) scmd += "()";
            if (CommandHandler::hasCommand(scmd.substring(0, scmd.indexOf('(')))) {
                os.execute(scmd);
            } else {
                Console::warn("Mission") << "Unknown cmd: " << cmd << Console::endl;
            }
        }
    }

    if (s_abort) {
        Console::warn("Mission") << "═══ Fallback strategy ABORTED ═══" << Console::endl;
    } else {
        Console::info("Mission") << "═══ Fallback strategy DONE ═══" << Console::endl;
    }

    s_running = false;
    s_abort   = false;
}

// ── SD write helpers — delegate to SDCard namespace (owns <SD.h>) ────────────

FLASHMEM bool sdOpen() {
    if (!SDCard::isReady()) return false;
    bool ok = SDCard::openWrite(FALLBACK_PATH);
    if (ok) Console::info("Mission") << "SD write session opened" << Console::endl;
    else    Console::error("Mission") << "Cannot create " << FALLBACK_PATH << Console::endl;
    return ok;
}

FLASHMEM bool sdAppendLine(const char* line) {
    return SDCard::appendLine(line);
}

FLASHMEM bool sdClose() {
    if (!SDCard::closeWrite()) return false;
    Console::info("Mission") << "SD write session closed. Reloading…" << Console::endl;
    return load();
}

} // namespace MissionController
