#pragma once
/**
 * services/mission/mission_controller.h — Fallback Mission Executor
 *
 * Executes a pre-defined strategy from SD card when the Jetson is
 * disconnected.  The strategy file (/mission_fallback.cfg) is a plain-text
 * list of firmware commands (one per line), generated by holOS.
 *
 * Usage from routines / fallback:
 *   MissionController::execute();   // blocking — runs until end or abort
 *   MissionController::abort();     // call from another thread / ISR-safe
 *
 * Format of /mission_fallback.cfg:
 *   # Comments start with #
 *   go(300,400)
 *   turn(90.0)
 *   delay(500)
 *   custom_actuator_cmd
 *   ...
 */

#include <Arduino.h>

namespace MissionController {

    static constexpr const char* FALLBACK_PATH = "/mission_fallback.cfg";
    static constexpr size_t      MAX_FILE_SIZE = 8192;   // 8 KB limit
    static constexpr size_t      MAX_LINE_LEN  = 128;

    /// Load the fallback strategy from SD. Returns true if at least one
    /// command was parsed. Must be called after SDCard::init().
    bool load();

    /// Returns true if a valid strategy is currently loaded.
    bool isLoaded();

    /// Execute the loaded strategy sequentially. Blocking call —
    /// runs until all commands are done or abort() is requested.
    void execute();

    /// Abort an in-progress execute(). Thread-safe (sets a flag).
    void abort();

    /// Returns true if execute() is currently running.
    bool isRunning();

    // ── SD write API (called by firmware commands mission_sd_open/line/close) ──

    /// Open /mission_fallback.cfg for writing (truncates existing file).
    bool sdOpen();

    /// Append one line of text to the open file.
    bool sdAppendLine(const char* line);

    /// Close the file and reload the strategy into RAM.
    bool sdClose();

} // namespace MissionController
